name: deploy to GHP

on:
  schedule:
    - cron: "0 0 * * 1" # every Monday at midnight UTC

  workflow_dispatch:  

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deployDatShiz:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Determine if this is an even week
        id: weekcheck
        run: |
          WEEK=$(date +%U)
          if (( WEEK % 2 == 0 )); then
            echo "run=true" >> $GITHUB_OUTPUT
            echo "proceeding with deploy"
          else
            echo "run=false" >> $GITHUB_OUTPUT
            echo "skipping deploy"
          fi

      - name: Checkout
        if: steps.weekcheck.outputs.run == 'true'
        uses: actions/checkout@v4

      - name: Setup Pages
        if: steps.weekcheck.outputs.run == 'true'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: steps.weekcheck.outputs.run == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        if: steps.weekcheck.outputs.run == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
